/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulador_de_consultas.screens;

/**
 *
 * @author mr.blissfulgrin
 */
public class Logger extends javax.swing.JFrame
{

    /**
     * Creates new form Logger
     */
    public Logger()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        administrador = new javax.swing.JButton();
        gestor = new javax.swing.JButton();
        empleado = new javax.swing.JButton();
        supervisor = new javax.swing.JButton();
        cliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.CardLayout(10, 10));

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BBDD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(12, 22, 13, 22);
        jPanel2.add(jLabel1, gridBagConstraints);

        administrador.setText("Administrador");
        administrador.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                administradorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 26, 4, 26);
        jPanel2.add(administrador, gridBagConstraints);

        gestor.setText("Gestor");
        gestor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                gestorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 26, 4, 26);
        jPanel2.add(gestor, gridBagConstraints);

        empleado.setText("Empleado");
        empleado.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                empleadoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 26, 4, 26);
        jPanel2.add(empleado, gridBagConstraints);

        supervisor.setText("Supervisor");
        supervisor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                supervisorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 26, 4, 26);
        jPanel2.add(supervisor, gridBagConstraints);

        cliente.setText("Cliente");
        cliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                clienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 26, 4, 26);
        jPanel2.add(cliente, gridBagConstraints);

        jPanel1.add(jPanel2, "card2");

        getContentPane().add(jPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void administradorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_administradorActionPerformed
    {//GEN-HEADEREND:event_administradorActionPerformed
        new Asker(0).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_administradorActionPerformed

    private void gestorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_gestorActionPerformed
    {//GEN-HEADEREND:event_gestorActionPerformed
        new Asker(1).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gestorActionPerformed

    private void empleadoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_empleadoActionPerformed
    {//GEN-HEADEREND:event_empleadoActionPerformed
        new Asker(2).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_empleadoActionPerformed

    private void supervisorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_supervisorActionPerformed
    {//GEN-HEADEREND:event_supervisorActionPerformed
        new Asker(3).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_supervisorActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clienteActionPerformed
    {//GEN-HEADEREND:event_clienteActionPerformed
        new Asker(4).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_clienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton administrador;
    private javax.swing.JButton cliente;
    private javax.swing.JButton empleado;
    private javax.swing.JButton gestor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton supervisor;
    // End of variables declaration//GEN-END:variables
}
