--UPDATE "Ticket" SET "Fecha_emision"='2010-08-27 22:16:46'
--WHERE "Ticket"."Fecha_emision"='2010-08-28 22:16:46'
--SELECT  "Codigo", "cantidad", "Articulo"."Precio_sin_IVA"
--FROM "Contiene" INNER JOIN "Articulo" ON "Contiene"."Codigo_Barras"="Articulo"."Codigo_Barras"
--GROUP BY "Codigo", "cantidad", "Articulo"."Precio_sin_IVA"